### ISSUE TITLE
App suddenly stops after onResume

### ISSUE THREAD

**Issue by migueljrodrigues** [thorbenprimke/realm-mapview#4]
Hi,

I am currently trying to use this code with my colleague @MiguelFale, and we noticed the following error when we resume the application.

Could you clarify what is happening and how could we solve this error?

Thanks!

FATAL EXCEPTION: main
                                                                                    Process: co.moonmonkeylabs.realmmap.example, PID: 12757
                                                                                    java.lang.IllegalStateException: Illegal State: Object is no longer valid to operate on. Was it deleted by another thread?
                                                                                        at io.realm.internal.UncheckedRow.nativeGetString(Native Method)
                                                                                        at io.realm.internal.UncheckedRow.getString(UncheckedRow.java:167)
                                                                                        at co.moonmonkeylabs.realmmapview.RealmClusterRenderer.onBeforeClusterItemRendered(RealmClusterRenderer.java:37)
                                                                                        at co.moonmonkeylabs.realmmapview.RealmClusterRenderer.onBeforeClusterItemRendered(RealmClusterRenderer.java:18)
                                                                                        at com.google.maps.android.clustering.view.DefaultClusterRenderer$CreateMarkerTask.perform(DefaultClusterRenderer.java:820)
                                                                                        at com.google.maps.android.clustering.view.DefaultClusterRenderer$CreateMarkerTask.access$2000(DefaultClusterRenderer.java:790)
                                                                                        at com.google.maps.android.clustering.view.DefaultClusterRenderer$MarkerModifier.performNextTask(DefaultClusterRenderer.java:629)
                                                                                        at com.google.maps.android.clustering.view.DefaultClusterRenderer$MarkerModifier.handleMessage(DefaultClusterRenderer.java:601)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                        at android.os.Looper.loop(Looper.java:149)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:5257)
                                                                                        at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                        at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
                                                                                        at dalvik.system.NativeStart.main(Native Method)

**Comment by thorbenprimke** [comment]
Based on the exception, the `Realm` was closed but the map still uses objects that are based on the old realm.

Two solutions: 
- Not to close the `Realm`
- Update the maps data with the new `Realm`

I'll to dig into it this weekend to figure out what the best solution is.
